Friendly error messages
=======================

AvantPy aims to provide friendlier feedback when an exception
is raised than what is done by Python.
Such feedback will also be available in languages other than English.

.. note::

     The content of this page is generated by running
     tb_pyupper.py located in the ``tests/`` directory.
     This needs to be done explicitly, independently of updating the
     documentation using Sphinx.

AvantPy version: 0.0.9
Python version: 3.7.3



IfNobreakError
--------------

Example::

    AvantPy exception: IfNobreakError

    Error found in file 'raise_if_nobreak.pyupper' on line 4.

    Dialect used: pyupper

       2: if True:
       3:     pass
    -->4: NOBREAK:

    The AvantPy 'NOBREAK' keyword cannot be used in
    an 'IF/ELIF/ELSE' clause (Python: if/elif/else).


IndentationError: expected an indented block
--------------------------------------------

Example::

    Python exception: 
        IndentationError: expected an indented block

    Error found in file 'raise_indentation_error1.pyupper' on line 3.

    Dialect used: pyupper

       1: '''Should raise IndentationError'''
       2: IF TRUE:
    -->3: PASS
       4: 

    An indentation error occurs when a given line is
    not indented (aligned vertically) as expected.
    In this case, the line indicated by an arrow
    was expected to begin a new indented block.


IndentationError: unexpected indent
-----------------------------------

Example::

    Python exception: 
        IndentationError: unexpected indent

    Error found in file 'raise_indentation_error2.pyupper' on line 4.

    Dialect used: pyupper

       1: '''Should raise IndentationError'''
       2: IF TRUE:
       3:     PASS
    -->4:       PASS
       5: 

    An indentation error occurs when a given line is
    not indented (aligned vertically) as expected.
    In this case, the line indicated by an arrow
    is more indented than expected and does not match
    the indentation of the previous line.


IndentationError - no match
---------------------------

Example::

    Python exception: 
        IndentationError: unindent does not match any outer indentation level

    Error found in file 'raise_indentation_error3.pyupper' on line 4.

    Dialect used: pyupper

       1: '''Should raise IndentationError'''
       2: IF TRUE:
       3:       PASS
    -->4:     PASS
       5: 

    An indentation error occurs when a given line is
    not indented (aligned vertically) as expected.
    In this case, the line indicated by an arrow
    is less indented the preceding one,
    and is not aligned vertically with another block of code.


MismatchedBracketsError
-----------------------

Example::

    AvantPy exception: MismatchedBracketsError

    Error found in file 'raise_mismatched_brackets.pyupper' on line 10.

    Dialect used: pyupper

    --> 2: a = (1,   # Large number of lines between ( and ]
        3:     2,
        4:     3, 4,
           ...
        8:     8,
        9:     9,
    -->10: ]

    The opening ( does not match the closing ].


MissingLeftBracketError
-----------------------

Example::

    AvantPy exception: MissingLeftBracketError

    Error found in file 'raise_missing_left_bracket.pyupper' on line 5.

    Dialect used: pyupper

       4:     3, 4,)
    -->5:     )
       6: b = 3

    The closing ) does not match anything.


MissingRepeatColonError
-----------------------

Example::

    AvantPy exception: MissingRepeatColonError

    Error found in file 'raise_missing_repeat_colon.pyupper' on line 3.

    Dialect used: pyupper

       2: x = 0
    -->3: REPEAT UNTIL (x ==
       4:          1):

    A statement beginning with the 'REPEAT' keyword must be on
    a single line ending with a colon (:) that indicates the beginning of
    an indented block of code, with no other colon appearing on that line.


MissingRepeatError
------------------

Example::

    AvantPy exception: MissingRepeatError

    Error found in file 'raise_missing_repeat.pyupper' on line 3.

    Dialect used: pyupper

       2: x = 0
    -->3: UNTIL x == 2:
       4:     x += 1

    The AvantPy 'UNTIL'' keyword can be used only when preceded by 'REPEAT'.


NameError
---------

Example::

    Python exception: 
        NameError: name 'c' is not defined

    Error found in file 'raise_name_error.pyupper' on line 4.

    Dialect used: pyupper

       3: a = 1
    -->4: b = c
       5: d = 3

    A NameError exception indicates that a variable or
    function name is not known to Python.
    Most often, this is because there is a spelling mistake; however,
    sometimes it is because it is used before being defined
    or given a value. In your program, the unknown name is 'c'.


NobreakFirstError
-----------------

Example::

    AvantPy exception: NobreakFirstError

    Error found in file 'raise_nobreak_first.pyupper' on line 3.

    Dialect used: pyupper

       2: # Need to prevent NOBREAK being replaced by 'else' in this situation.
    -->3: a = 1 if True NOBREAK 3
       4: 

    The AvantPy 'NOBREAK' keyword can be used instead of 'ELSE'
    (Python: else) only when it begins a new statement in
    'FOR/WHILE' loops (Python: for/while).


NobreakSyntaxError
------------------

Example::

    AvantPy exception: NobreakSyntaxError

    Error found in file 'raise_nobreak_syntax.pyupper' on line 4.

    Dialect used: pyupper

       3: a = 1
    -->4: NOBREAK: pass
       5: 

    The AvantPy 'NOBREAK' keyword can only be used as a replacement
    of 'ELSE' (Python: else) with a matching 'FOR' or
    'WHILE' loop (Python: for/while).


RepeatFirstError
----------------

Example::

    AvantPy exception: RepeatFirstError

    Error found in file 'raise_repeat_first.pyupper' on line 3.

    Dialect used: pyupper

       2: # Catch an early case of using REPEAT not to begin a loop
    -->3: a = REPEAT
       4: 

    The AvantPy 'REPEAT' keyword can only be used to begin
    a new loop (Python: equivalent to 'for' or 'while' loop).


TabError
--------

Example::

    Python exception: 
        TabError: inconsistent use of tabs and spaces in indentation

    Error found in file 'raise_tab_error.pyupper' on line 3.

    Dialect used: pyupper

       1: """Should raise TabError"""
       2: 
    -->3: exec("""if True:\n        pass\n\tpass""")
       4: 

    A TabError indicates that you have used both spaces
    and tab characters to indent your code.
    This is not allowed in Python.
    Python's recommendation is to always use spaces to indent your code.


TryNobreakError
---------------

Example::

    AvantPy exception: TryNobreakError

    Error found in file 'raise_try_nobreak.pyupper' on line 7.

    Dialect used: pyupper

       3:     TRY:
       4:         A = 1
       5:     EXCEPT:
       6:         A = 2
    -->7:     NOBREAK:

    The AvantPy 'NOBREAK' keyword cannot be used in
    a 'TRY/EXCEPT/ELSE/FINALLY' clause
    (Python: try/except/else/finally).


UnknownDialectError
-------------------

Example::

    AvantPy exception: UnknownDialectError

    The following unknown dialect was requested: pyxx.

    The known dialects are: ['pyen', 'pyes', 'pyfr', 'pyupper'].


UnknownLanguageError
--------------------

Example::

    AvantPy exception: UnknownLanguageError

    The following unknown language was requested: xx.

    The known languages are: {'en', 'fr'}.

