# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2019-04-06 15:26-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=cp1252\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: console.py:95
msgid "UNHANDLED EXCEPTION in console.py. This should not happen."
msgstr ""

#: exception_handling.py:19
msgid ""
"    AvantPy exception: {exception_name}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
msgstr ""

#: exception_handling.py:25
msgid ""
"    AvantPy exception: {exception_name}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"{partial_source}\n"
"\n"
msgstr ""

#: exception_handling.py:30
msgid ""
"    Python exception: \n"
"        {python_display}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
msgstr ""

#: exception_handling.py:37
msgid ""
"    Python exception: \n"
"        {python_display}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"{partial_source}\n"
"\n"
msgstr ""

#: exception_handling.py:126
msgid ""
"An exception was raised for which we have no simplified traceback:\n"
msgstr ""

#: exception_handling.py:169
msgid ""
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    an if/elif/else clause.\n"
"\n"
msgstr ""

#: exception_handling.py:174
msgid ""
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    an '{if_kwd}/{elif_kwd}/{else_kwd}' clause (Python: if/elif/else).\n"
"\n"
msgstr ""

#: exception_handling.py:197
msgid ""
"    In this case, the line indicated by an arrow\n"
"    is more indented than expected and does not match\n"
"    the indentation of the previous line.\n"
"\n"
msgstr ""

#: exception_handling.py:203
msgid ""
"    In this case, the line indicated by an arrow\n"
"    was expected to begin a new indented block.\n"
"\n"
msgstr ""

#: exception_handling.py:208
msgid ""
"    In this case, the line indicated by an arrow\n"
"    is less indented the preceding one,\n"
"    and is not aligned vertically with another block of code.\n"
"\n"
msgstr ""

#: exception_handling.py:225
msgid ""
"    An indentation error occurs when a given line is\n"
"    not indented (aligned vertically) as expected.\n"
"{this_case}\n"
"\n"
msgstr ""

#: exception_handling.py:259
msgid ""
"    The opening {open_bracket} does not match the closing {close_bracket}.\n"
"\n"
msgstr ""

#: exception_handling.py:292
msgid ""
"    The closing {bracket} does not match anything.\n"
"\n"
msgstr ""

#: exception_handling.py:320
msgid ""
"    A statement beginning with the '{repeat_kwd}' keyword must be on\n"
"    a single line ending with a colon (:) that indicates the beginning of\n"
"    an indented block of code, with no other colon appearing on that line.\n"
"\n"
msgstr ""

#: exception_handling.py:348
msgid ""
"    The AvantPy '{keyword}'' keyword can be used only when preceded by '{repeat_kwd}'.\n"
"\n"
msgstr ""

#: exception_handling.py:379
msgid ""
"    A NameError exception indicates that a variable or\n"
"    function name is not known to Python.\n"
"    Most often, this is because there is a spelling mistake; however,\n"
"    sometimes it is because it is used before being defined\n"
"    or given a value. In your program, the unknown name is '{var_name}'.\n"
"\n"
msgstr ""

#: exception_handling.py:415
msgid ""
"    The AvantPy '{nobreak_kwd}' keyword can be used instead of '{else_kwd}'\n"
"    (Python: else) only when it begins a new statement in\n"
"    '{for_kwd}/{while_kwd}' loops (Python: for/while).\n"
"\n"
msgstr ""

#: exception_handling.py:446
msgid ""
"    The AvantPy '{nobreak_kwd}' keyword can only be used as a replacement\n"
"    of '{else_kwd}' (Python: else) with a matching '{for_kwd}' or\n"
"    '{while_kwd}' loop (Python: for/while).\n"
"\n"
msgstr ""

#: exception_handling.py:477
msgid ""
"    The AvantPy '{repeat_kwd}' keyword can only be used to begin\n"
"    a new loop (Python: equivalent to 'for' or 'while' loop).\n"
"\n"
msgstr ""

#: exception_handling.py:503
msgid ""
"    The AvantPy '{nobreak_kwd}' keyword cannot be used in\n"
"    a '{try_kwd}/{except_kwd}/{else_kwd}/{finally_kwd}' clause\n"
"    (Python: try/except/else/finally).\n"
"\n"
msgstr ""

#: exception_handling.py:530
msgid ""
"    AvantPy exception: UnknownDialectError\n"
"\n"
"    The following unknown dialect was requested: {dialect}.\n"
"\n"
"    The known dialects are: {all_dialects}.\n"
"\n"
msgstr ""

#: exception_handling.py:548
msgid ""
"    AvantPy exception: UnknownLanguageError\n"
"\n"
"    The following unknown language was requested: {lang}.\n"
"\n"
"    The known languages are: {all_langs}.\n"
"\n"
msgstr ""

#: import_hook.py:36
msgid "Cannot find main module: "
msgstr ""

#: session.py:168
msgid "    ==> Language: {lang} | AvantPy dialect: {dialect}"
msgstr ""

