# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2019-03-31 08:31-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=cp1252\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: console.py:95
msgid "UNHANDLED EXCEPTION in console.py. This should not happen."
msgstr ""

#: exception_handling.py:79
msgid ""
"An exception was raised for which we have no simplified traceback:\n"
msgstr ""

#: exception_handling.py:130
msgid ""
"\n"
"    AVANTPY EXCEPTION: IfNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy {nobreak_kwd} keyword cannot be used in\n"
"    an IF/ELIF/ELSE clause (Python: if/elif/else).\n"
"\n"
msgstr ""

#: exception_handling.py:167
msgid ""
"\n"
"    AVANTPY EXCEPTION: MismatchedBracketsError\n"
"\n"
"    Error found in file '{filename}' on lines [{begin} - {end}].\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The opening {open_bracket} does not match the closing {close_bracket}.\n"
"\n"
msgstr ""

#: exception_handling.py:202
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingLeftBracketError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The closing {bracket} does not match anything.\n"
"\n"
msgstr ""

#: exception_handling.py:237
msgid ""
"\n"
"    AVANTPY EXCEPTION: MissingRepeatError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy {keyword} keyword can be used only when preceded by REPEAT.\n"
"\n"
msgstr ""

#: exception_handling.py:283
msgid ""
"\n"
"    PYTHON EXCEPTION: {python_display}\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    A NameError exception indicates that a variable or\n"
"    function name is not known to Python.\n"
"    Most often, this is because there is a spelling mistake; however,\n"
"    sometimes it is because it is used before being defined or given a value.\n"
"    In your program, the unknown name is '{var_name}'.\n"
"\n"
msgstr ""

#: exception_handling.py:323
msgid ""
"\n"
"    AVANTPY EXCEPTION: NobreakFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy {nobreak_kwd} keyword can be used instead of ELSE\n"
"    (Python: else) only when it begins a new statement in FOR/WHILE loops.\n"
"\n"
msgstr ""

#: exception_handling.py:360
msgid ""
"\n"
"    AVANTPY EXCEPTION: NobreakSyntaxError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy {nobreak_kwd} keyword can only be used as a replacement\n"
"    of ELSE (Python: else) with a matching FOR or WHILE loop\n"
"    (Python: for/while).\n"
"\n"
msgstr ""

#: exception_handling.py:397
msgid ""
"\n"
"    AVANTPY EXCEPTION: RepeatFirstError\n"
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy {repeat_kwd} keyword can only be used to begin\n"
"    a new loop (Python: equivalent to 'for' or 'while' loop).\n"
"\n"
msgstr ""

#: exception_handling.py:433
msgid ""
"\n"
"    AVANTPY EXCEPTION: TryNobreakError\n"
"\n"
"    Error found in file '{filename}' on line {nobreak_linenumber}.\n"
"\n"
"    Dialect used: {dialect}\n"
"\n"
"{partial_source}\n"
"\n"
"    The AvantPy {nobreak_kwd} keyword cannot be used in\n"
"    a TRY/EXCEPT/ELSE/FINALLY clause (Python: try/except/else/finally).\n"
"\n"
msgstr ""

#: exception_handling.py:457
msgid ""
"\n"
"    AVANTPY EXCEPTION: UnknownDialectError\n"
"\n"
"    The following unknown dialect was requested: {dialect}.\n"
"\n"
"    The known dialects are: {all_dialects}.\n"
"\n"
msgstr ""

#: exception_handling.py:477
msgid ""
"\n"
"    AVANTPY EXCEPTION: UnknownLanguageError\n"
"\n"
"    The following unknown language was requested: {lang}.\n"
"\n"
"    The known languages are: {all_langs}.\n"
"\n"
msgstr ""

#: import_hook.py:36
msgid "Cannot find main module: "
msgstr ""

#: session.py:168
msgid "    ==> LANGUAGE: {lang} | AVANTPY DIALECT: {dialect}"
msgstr ""

